### ISSUE TITLE
Do not show 'Auto' when hls is not available

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flowplayer-quality-selector#13]
http://flowplayer.blacktrash.org/fp6/qsel-playlist.html
'Auto' is still visible, but not selectable (good), in the following situations:
- turn off Flash
- remove a hls source
- specify `engine: "html5"` for hls source

The only way to turn off 'Auto' display is to set `swfHls: false` on player level.

That's particularly unintuitive when hlsjs is loaded and no hls source is present (same behavior).

**Comment by bbbo** [comment]
@blacktrash do the commits in https://github.com/flowplayer/flowplayer/issues/1080 fix the issue?

**Comment by phloxic** [comment]
@bbbo
- the quality selector is not to be used with Flowplayer 7
- the vod quality selector does not have the problem

**Comment by bbbo** [comment]
yeah, but the quality selector is still used in the Wordpress plugin for FP6 users for example...

**Comment by phloxic** [comment]
I can have a look, but iirc that's rather complex. the quality selector is very much confined to Drive, where a HLS source is always present as well.

**Comment by phloxic** [comment]
Should be fixed. Closing.
